# Generated by Django 3.0.3 on 2020-02-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_connection', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.UniqueConstraint(fields=('friend1', 'friend1'), name='friend1_friend2_unique_constraint'),
        ),
    ]
